app/blueprints/routes.py
from app.forms import CommentForm
from flask import Blueprint,render_template,redirect,url_for,flash,request,abort,g
from app.extensions import db
from app.models import Category,Comment,Article,Tag,Notification
from app.utils import redirect_back,change_user_pic
from flask_login import current_user,login_required
from app.forms import AccountForm,SearchForm
from app.notifications import comment_notification

routes = Blueprint('routes',__name__)

@routes.before_app_request
def before_request():
    g.search_form = SearchForm()


@routes.route('/')
def home():
    review_category = Category.query.filter_by(name='Reviews').first()
    platform_category = Category.query.filter_by(name='Platform').first()
    hardware_category = Category.query.filter_by(name='Hardware').first()
    dissection_category = Category.query.filter_by(name='Dissection').first()
    tech_category = Category.query.filter_by(name='Tech').first()
    page = request.args.get('page',1,type=int)
    latest = Article.query.order_by(Article.timestamp.desc()).paginate(page=page,per_page=15)
    reviews = Article.query.with_parent(review_category).paginate(page,per_page=4)
    hardware = Article.query.with_parent(hardware_category).paginate(page,per_page=4)
    dissection = Article.query.with_parent(dissection_category).paginate(page,per_page=5)
    platform = Article.query.with_parent(platform_category).paginate(page,per_page=4)
    tech = Article.query.with_parent(tech_category).paginate(page, per_page=5)
    tags = Tag.query.paginate(page,per_page=10)
    return render_template('routes/home.html',latest=latest,reviews=reviews,hardware=hardware,dissection=dissection,
    platform=platform,tech=tech,tags=tags)


@routes.route('/about')
def about():
    return render_template('routes/about.html')


@routes.route('/account',methods=['POST','GET'])
@login_required
def account():
    form = AccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        if current_user.is_admin:
            current_user.about = form.about.data
        if form.profile_pic.data:
            current_user.profile_pic = change_user_pic(form.profile_pic.data)
        db.session.commit()
        flash('Your Info Has Been Updated','success')
        return redirect(url_for('routes.account'))
    else:
        form.username.data = current_user.username
        form.email.data = current_user.email
        if current_user.is_admin:
            form.about.data = current_user.about
    return render_template('routes/account.html', form=form)


@routes.route('/show/articles')
def show_articles():
    page =request.args.get('page',1,type=int)
    articles = Article.query.order_by(Article.timestamp.desc()).paginate(page,per_page=10)
    return render_template('routes/show_articles.html',articles=articles)


@routes.route('/show/category/<int:category_id>')
def show_category(category_id):
    page = request.args.get('page', 1, type=int)
    category = Category.query.get_or_404(category_id)
    articles = Article.query.with_parent(category).order_by(Article.timestamp.desc()).paginate(page, per_page=8)
    return render_template('routes/show_articles.html', articles=articles, selector=category,type='category')


@routes.route('/show/tag/<int:tag_id>')
def show_tag(tag_id):
    page = request.args.get('page', 1, type=int)
    tag = Tag.query.get_or_404(tag_id)
    articles = Article.query.with_parent(tag).order_by(Article.timestamp.desc()).paginate(page, per_page=8)
    return render_template('routes/show_articles.html', articles=articles, selector=tag, type='tag')


@routes.route('/show/review/all')
def show_reviews():
    page = request.args.get('page', 1, type=int)
    articles = Article.query.filter_by(is_review=True).order_by(Article.timestamp.desc()).paginate(page, per_page=8)
    return render_template('routes/show_articles.html', articles=articles,type='reviews')


@routes.route('/show/article/<int:article_id>',methods=['POST','GET'])
def show_article(article_id):
    article = Article.query.get_or_404(article_id)
    article.views_count+=1
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,author=current_user,article=article)
        db.session.add(comment)
        db.session.commit()
        flash('Comment Added','success')
        return redirect(url_for('routes.show_article',article_id=article_id))
    return render_template('routes/show_article.html', article=article,form=form)


@routes.route('/comment/reply/<int:comment_id>',methods=['POST','GET'])
@login_required
def reply_comment(comment_id):
    comment =Comment.query.get_or_404(comment_id)
    form = CommentForm()
    if form.validate_on_submit():
        reply_comment = Comment(body=form.body.data,author=current_user)
        db.session.add(reply_comment)
        comment.replies.append(reply_comment)
        notification = comment_notification(article_id=comment.article.id, receiver=comment.author)
        db.session.add(notification)
        db.session.commit()
        flash('Replay Added','success')
        return redirect_back()
    return render_template('routes/comment.html',form=form,comment=comment)


@routes.route('/comment/edit/<int:comment_id>',methods=['POST','GET'])
@login_required
def edit_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.author:
        abort(403)
    form = CommentForm()
    if form.validate_on_submit():
        comment.body =form.body.data
        db.session.commit()
        flash('Comment Updated','success')
        return redirect_back()
    form.body.data = comment.body
    return render_template('routes/comment.html',form=form,comment=comment)


@routes.route('/comment/delete/<int:comment_id>')
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.author:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('comment deleted','success')
    return redirect_back()


@routes.route('/notifications')
@login_required
def show_notifications():
    filter = request.args.get('filter')
    if filter=='all':
        notifications = Notification.query.all()
    elif filter=='unread':
        notifications = Notification.query.filter_by(is_read=False).all()
    return render_template('routes/notifications.html', notifications=notifications)

@routes.route('/read/notification/<int:notification_id>')
@login_required
def read_notification(notification_id):
    notification=Notification.query.get_or_404(notification_id)
    notification.is_read = True
    db.session.commit()
    flash('notifications archived.', 'success')
    return redirect(url_for('routes.show_notifications'))

@routes.route('/read/notification/all')
@login_required
def read_all_notification():
    for notification in current_user.notification:
        notification.is_read = True
    db.session.commit()
    flash('All notifications archived.', 'success')
    return redirect(url_for('routes.show_notifications'))


@routes.route('/search')
def search():
    if not g.search_form.validate():
        return redirect_back()
    
    page = request.args.get('page',1,type=int)
    articles,total = Article.search(g.search_form.q.data,page,10)
    next_url = url_for('routes.search',q=g.search_form.q.data,page=page+1) if total> page*10 else None
    prev_url = url_for('routes.search', q=g.search_form.q.data,page=page-1) if page>1 else None

    return render_template('search.html',articles=articles,next_url=next_url,prev_url=prev_url)
    

app/templates/routes/about.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

app/templates/routes/account.html
{%extends 'index.html'%}
{%block title%}Account{%endblock%}
{%block content%}

<div class="signup-section">
        <div style="text-align: center;margin-top: 10px;">
        <img class="rounded mx-auto d-block" src="{{url_for('static',filename='user/'+current_user.profile_pic)}}">
          <h2 class="account-heading">{{ current_user.username }}</h2>
</div>
    <div class="signup-text">
        <div class="container">
            <div class="signup-title">
                <h2>Account</h2>
            </div>
            <form method="POST" class="signup-form" enctype='multipart/form-data'>
                {{form.hidden_tag()}}
                <div class="sf-input-list">
                    {%if form.username.errors%}
                    {{form.username(class='input-value is-invalid',placeholder='Username')}}

                    <div class="invalid-feedback">
                        {%for error in form.username.errors%}
                        <span>{{error}}</span>
                    </div>
                    {%endfor%}
                    {%else%}
                    {{form.username(class='input-value',placeholder='Username')}}
                    {%endif%}

                    {%if form.email.errors%}
                    {{form.email(class='input-value is-invalid',placeholder='Email')}}

                    <div class="invalid-feedback">
                        {%for error in form.email.errors%}
                        <span>{{error}}</span>
                    </div>
                    {%endfor%}
                    {%else%}
                    {{form.email(class='input-value',placeholder='Email')}}
                    {%endif%}

                    {%if current_user.is_admin%}
                    {%if form.about.errors%}
                    {{form.about(class='input-value is-invalid',placeholder='About')}}

                    <div class="invalid-feedback">
                        {%for error in form.about.errors%}
                        <span>{{error}}</span>
                    </div>
                    {%endfor%}
                    {%else%}
                    {{form.about(class='input-value',placeholder='About')}}
                    {%endif%}
                    {%endif%}

                    {{ form.profile_pic.label() }}
                    {{ form.profile_pic(class="form-control-file") }}
                    {% if form.profile_pic.errors %}
                        {% for error in form.profile_pic.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}
                {{form.submit()}}
            </form>
        </div>
    </div>
</div>
{%endblock%}

app/templates/routes/comment.html
{%extends 'index.html'%}

{%block title%}Home{%endblock%}
{%block content%}
<div class="signup-section">
    <div class="signup-text">
        <div class="container">
            <div class="signup-title">
                <h2>Comment</h2>
            </div>
            <form method="POST" class="signup-form">
                {{form.hidden_tag()}}
                <div class="sf-input-list">
                    {%if form.body.errors%}
                    {{form.body(class='input-value is-invalid',placeholder='Comment')}}

                    <div class="invalid-feedback">
                        {%for error in form.body.errors%}
                        <span>{{error}}</span>
                    </div>
                    {%endfor%}
                    {%else%}
                    {{form.body(class='input-value',placeholder='Comment')}}
                    {%endif%}
                {{form.submit()}}
            </form>
        </div>
    </div>
</div>
{%endblock%}

app/templates/routes/notifications.html
{% extends 'index.html' %}
{% block title %}Notifications{% endblock %}

{% block content %}
<section class='dark-theme'>
    <div class="page-header">
        <h1>Notifications</h1>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="nav nav-pills flex-column" role="tablist" aria-orientation="vertical">
                <a class="nav-item nav-link {% if request.args.get('filter') != 'unread' %}active{% endif %}"
                   href="{{ url_for('routes.show_notifications', filter='all') }}">
                    All
                </a>
                <a class="nav-item nav-link {% if request.args.get('filter') == 'unread' %}active{% endif %}"
                   href="{{ url_for('routes.show_notifications', filter='unread') }}">
                    Unread
                </a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="card w-100">
                <div class="card-header">{{ notification_count }} unread notifications
                    <div class="float-right">
                        <a class="inline" href="{{ url_for('routes.read_all_notification') }}">
                                <span class="fa fa-check" aria-hidden="true"></span> Read all
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    {% if notifications %}
                        <ul class="list-group">
                            {% for notification in notifications %}
                                <li class="list-group-item">
                                    {{ notification.body |safe}}
                                    <span class="float-right">
                                        {{notification.timestamp|dateformater }}
                                        {% if notification.is_read == False %}
                                            <a class="inline"href="{{ url_for('routes.read_notification', notification_id=notification.id) }}">
                                                    <span class="fa fa-check" aria-hidden="true"></span>
                                            </a>
                                        {% endif %}
                                    </span>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <div class="tip text-center">
                            <h6>No notifications.</h6>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </section>
{% endblock %}

app/templates/routes/search.html
{%extends 'index.html'%}
{%block title%}Search{%endblock%}
{%block content%}
    <section class="breadcrumb-section set-bg spad" data-setbg="{{url_for('static',filename='article/breadcrumb-bg.jpg')}}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        <h3><span>Search Result</span></h3>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="categories-grid-section spad">
        <div class="container">
            <div class="row">
                <div class="p-0">
                    <div class="row">
                        {%for article in articles.items%}
                        <div class="col-lg-6">
                            <div class="cg-item">
                                <div class="cg-pic set-bg" data-setbg="{{url_for('static',filename='article/'+article.article_pic)}}">
                                {%for category in article.category[:1]%}
                                    <div class="label" >
                                        <span>{{category.name}}</span>
                                    </div>
                                {%endfor%}
                                </div>
                                <div class="cg-text">
                                    <h5><a href="{{url_for('routes.show_article',article_id=article.id)}}">{{article.title[:20]}}...</a></h5>
                                    <ul>
                                        <li>by <span>{{article.author.username}}</span></li>
                                        <li><i class="fa fa-clock-o"></i> {{article.timestamp|dateformater}}</li>
                                        <li><i class="fa fa-comment-o"></i> {{article.comments.count()}}</li>
                                    </ul>
                                    <p>{{article.body[:50]}}...</p>
                                </div>
                            </div>
                        </div>
                        {%endfor%}
                    </div>
                    <div class="pagination-item">
                        {%for page_num in articles.iter_pages(left_edge=1,right_edge=1,left_current=2,right_current=2)%}
                        {%if prev_url%}
                            <a href="{{prev_url}}"><span>{{page_num}}</span></a>
                        {%elif next_url%}
                            <a href="{{next_url}}"><span>{{page_num}}</span></a>
                        {%endif%}
                        {%endfor%}
                    </div>
                </div>
            </div>
        </div>
    </section>
{%endblock%}

app/templates/routes/show_article.html
{%extends 'index.html'%}
{%block title%}{{article.title}}{%endblock%}
{%block content%}
<section class="details-hero-section set-bg" data-setbg="{{url_for('static',filename='article/'+ article.article_pic)}}">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="details-hero-text">
                    {%for category in article.category%}
                    <div class="label"><a href="{{url_for('routes.show_category',category_id=category.id)}}"><span>{{category.name}}</span></a></div>
                    {%endfor%}
                    <h3>{{article.title}}</h3>
                    <ul>
                        <li>by <span>{{article.author.username}}</span></li>
                        <li><i class="fa fa-clock-o"></i>{{article.timestamp|dateformater}}</li>
                        <li><i class="fa fa-comment-o"></i> {{article.comments.count()}}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Details Hero Section End -->

<!-- Details Post Section Begin -->
<section class="details-post-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 p-0">
                <div class="details-text">
                    <div class="dt-last-desc">
                        <p>{{article.body}}</p>
                    </div>
                    {%if article.review_score%}
                    <div class="dt-overall-rating">
                        <div class="or-heading">
                            <div class="or-item">
                                <div class="or-loader">
                                    <div class="loader-circle-wrap">
                                        <div class="loader-circle">
                                            <span class="circle-progress-2" data-cpid="id-5"
                                                data-cpvalue="{{article.review_score * 10}}"
                                                data-cpcolor="#c20000"></span>
                                            <div class="review-point">
                                                <div>{{article.review_score}}</div>
                                                <span>AVERAGE SCORE</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {%endif%}
                    <div class="dt-tags">
                        {%for tag in article.tags%}
                        <a href="{{url_for('routes.show_tag',tag_id=tag.id)}}"><span>{{tag.name}}</span></a>
                        {%endfor%}
                    </div>
                    <div class="dt-share">
                        <div class="ds-title">Share</div>
                        <div class="ds-links">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                        </div>
                    </div>
                    <div class="dt-author">
                        <div class="da-pic">
                            <img src="{{url_for('static',filename='user/'+article.author.profile_pic)}}" alt="">
                        </div>
                        <div class="da-text">
                            <h5>{{article.author.username}}</h5>
                            <p>{{article.author.about}}</p>
                            <div class="da-links">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-google-plus"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                                <a href="#"><i class="fa fa-youtube-play"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="dt-comment">
                        <h4>{{article.comments.count()}} comment</h4>
                        {%if article.comments%}
                        {%for comment in article.comments%}
                        <div class="dc-item">
                            <div class="dc-pic">
                                <img src="{{url_for('static',filename='user/'+comment.author.profile_pic)}}" alt="">
                            </div>
                            <div class="dc-text">
                                <h5>{{comment.author.username}}</h5>
                                <span class="c-date">{{comment.timestamp|dateformater}}</span>
                                <p>{{comment.body}}</p>
                                <div class = 'actions_buttons'>
                                <a href="{{url_for('routes.reply_comment',comment_id=comment.id)}}"
                                    class="reply-btn"><span>Reply</span></a>
                                {%if current_user==comment.author or current_user.is_admin%}
                                <a href="{{url_for('routes.edit_comment',comment_id=comment.id)}}"
                                    class="reply-btn" style="background-color: rgb(87, 87, 209);"><span>Edit</span></a>
                                <a href="{{url_for('routes.delete_comment',comment_id=comment.id)}}"
                                    class="reply-btn" style="background-color: red;"><span>Delete</span></a>
                                {%endif%}
                                </div>
                            </div>
                        </div>
                        {%for reply in comment.replies%}
                        <div class="dc-item reply-item">
                            <div class="dc-pic">
                                <img src="{{url_for('static',filename='user/'+reply.author.profile_pic)}}" alt="">
                            </div>
                            <div class="dc-text">
                                <h5>{{reply.author.username}}</h5>
                                <span class="c-date">{{reply.timestamp|dateformater}}</span>
                                <p>{{reply.body}}</p>
                            </div>
                        </div>
                        {%endfor%}
                        {%endfor%}
                        {%endif%}
                    </div>
                    {%if current_user.is_authenticated%}
                    <div class="dt-leave-comment">
                        <h4>Leave a comment</h4>
                        <form action="#" method="POST">
                            {{form.hidden_tag()}}
                            <div class="input-list">
                                {%if form.body.errors%}
                                {{form.body(class='input-value is-invalid',placeholder='Comment')}}

                                <div class="invalid-feedback">
                                {%for error in form.body.errors%}
                                    <span>{{error}}</span>
                                {%endfor%}
                                </div>
                                {%else%}
                                {{form.body(class='input-value',placeholder='Comment')}}
                                {%endif%}
                            </div>
                            {{form.submit()}}
                        </form>
                    </div>
                    {%endif%}
                </div>
            </div>
        </div>
    </div>
</section>
{%endblock%}

app/templates/routes/show_articles.html
{%extends 'index.html'%}
{%block title%}Articles{%endblock%}
{%block content%}
    <section class="breadcrumb-section set-bg spad" data-setbg="{{url_for('static',filename='article/breadcrumb-bg.jpg')}}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        {%if selector%}
                        <h3><span>{{selector.name}}</span></h3>
                        {%else%}
                        <h3><span>Articles</span></h3>
                        {%endif%}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="categories-grid-section spad">
        <div class="container">
            <div class="row">
                <div class="p-0">
                    <div class="row">
                        {%for article in articles.items%}
                        <div class="col-lg-6">
                            <div class="cg-item">
                                <div class="cg-pic set-bg" data-setbg="{{url_for('static',filename='article/'+article.article_pic)}}">
                                {%for category in article.category[:1]%}
                                    <div class="label" >
                                    <a href="{{url_for('routes.show_category',category_id=category.id)}}"><span>{{category.name}}</span></a>
                                    </div>
                                {%endfor%}
                                </div>
                                <div class="cg-text">
                                    <h5><a href="{{url_for('routes.show_article',article_id=article.id)}}">{{article.title[:20]}}...</a></h5>
                                    <ul>
                                        <li>by <span>{{article.author.username}}</span></li>
                                        <li><i class="fa fa-clock-o"></i> {{article.timestamp|dateformater}}</li>
                                        <li><i class="fa fa-comment-o"></i> {{article.comments.count()}}</li>
                                    </ul>
                                    <p>{{article.body[:50]}}...</p>
                                </div>
                            </div>
                        </div>
                        {%endfor%}
                    </div>
                    <div class="pagination-item">
                        {%for page_num in articles.iter_pages(left_edge=1,right_edge=1,left_current=2,right_current=2)%}
                        {%if page_num%}
                        {%if type=='category'%}
                            <a href="{{url_for('routes.show_category',page=page_num,category_id=selector.id)}}"><span>{{page_num}}</span></a>
                        {%elif type=='tag'%}
                            <a href="{{url_for('routes.show_tag',page=page_num,tag_id=selector.id)}}"><span>{{page_num}}</span></a>
                        {%elif type=='reviews'%}
                            <a href="{{url_for('routes.show_reviews',page=page_num)}}"><span>{{page_num}}</span></a>
                        {%else%}
                            <a href="{{url_for('routes.show_articles',page=page_num)}}"><span>{{page_num}}</span></a>
                        {%endif%}
                        {%else%}
                        <a href="#"><span>Next</span></a>
                        {%endif%}
                        {%endfor%}
                    </div>
                </div>
            </div>
        </div>
    </section>
{%endblock%}