app/blueprints/auth.py
from flask import Blueprint,redirect,render_template,request,url_for,flash
from flask_login import login_required,login_user,logout_user
from app.decorators import check_login
from app.utils import generate_token,verify_token
from app.forms import LoginForm,RegisterForm,ResetRequestForm,ChangePasswordForm
from app.models import User
from app.extensions import db
from app.oauth import OAuthSignIn
from app.emails import send_reset_token
from app.notifications import security_notification

auth =Blueprint('auth',__name__)


@auth.route('/login',methods=['POST','GET'])
@check_login
def login():
    form=LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if user.verify_password(form.password.data):
                login_user(user,remember=form.remember.data)
                flash('Logged In Successfully','success')
                next_des = request.args.get('next')
                return redirect(next_des) if next_des else redirect(url_for('routes.home'))
            else:
                flash('Wrong Password','danger')
        else:
            flash('User not found','danger')
    return render_template('auth/login.html',form=form)


@auth.route('/register',methods=['POST','GET'])
@check_login
def register():
    form=RegisterForm()
    if form.validate_on_submit():
        user = User(username=form.username.data,email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Registed Successfully Now You Can Login','success')
        return redirect(url_for('auth.login'))
    return render_template('auth/register.html',form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged Out User','success')
    return redirect(url_for('routes.about'))


@auth.route('/authorize/<provider_name>')
def oauth_authorize(provider_name):
    provider = OAuthSignIn.get_provider(provider_name)
    return provider.authorize()


@auth.route('/callback/<provider>')
def oauth_callback(provider):
    oauth =OAuthSignIn.get_provider(provider)
    social_id ,name,email = oauth.callback(provider)
    if social_id is None:
        flash('Authentication Failed','danger')
        return redirect(url_for('auth.login'))
    
    user = User.query.filter_by(social_id=social_id).first()
    if not user:
        user = User(username=name,email=email,social_id=social_id)
        db.session.add(user)
        db.session.commit()
    login_user(user,True)
    flash('Logged In Successfully','success')
    return redirect(url_for('routes.home'))

@auth.route('/reset/request',methods=['POST','GET'])
def reset_request():
    form = ResetRequestForm()
    if form.validate_on_submit():
        user= User.query.filter_by(email=form.email.data).first()
        if not user:
            flash('User Does Not Exists','danger')
        token = generate_token(user)
        send_reset_token(token,user)
        flash('Email Sent With Instrutions To Reset Password','success')
        return redirect(url_for('auth.login'))
    return render_template('auth/reset_request.html',form=form)


@auth.route('/reset/password/<token>',methods=['POST','GET'])
def reset_password(token):
    user=verify_token(token)
    if not user:
        flash('Invalid Or Expired Token', 'danger')
        return redirect(url_for('auth.forget_password'))
    form= ChangePasswordForm()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash('Password Has Been Changed', 'success')
        return redirect(url_for('auth.login'))
    return render_template('auth/reset_password.html', form=form)

app/blueprints/routes.py
from app.forms import CommentForm
from flask import Blueprint,render_template,redirect,url_for,flash,request,abort,g
from app.extensions import db
from app.models import Category,Comment,Article,Tag,Notification
from app.utils import redirect_back,change_user_pic
from flask_login import current_user,login_required
from app.forms import AccountForm,SearchForm
from app.notifications import comment_notification

routes = Blueprint('routes',__name__)

@routes.before_app_request
def before_request():
    g.search_form = SearchForm()


@routes.route('/')
def home():
    review_category = Category.query.filter_by(name='Reviews').first()
    platform_category = Category.query.filter_by(name='Platform').first()
    hardware_category = Category.query.filter_by(name='Hardware').first()
    dissection_category = Category.query.filter_by(name='Dissection').first()
    tech_category = Category.query.filter_by(name='Tech').first()
    page = request.args.get('page',1,type=int)
    latest = Article.query.order_by(Article.timestamp.desc()).paginate(page=page,per_page=15)
    reviews = Article.query.with_parent(review_category).paginate(page,per_page=4)
    hardware = Article.query.with_parent(hardware_category).paginate(page,per_page=4)
    dissection = Article.query.with_parent(dissection_category).paginate(page,per_page=5)
    platform = Article.query.with_parent(platform_category).paginate(page,per_page=4)
    tech = Article.query.with_parent(tech_category).paginate(page, per_page=5)
    tags = Tag.query.paginate(page,per_page=10)
    return render_template('routes/home.html',latest=latest,reviews=reviews,hardware=hardware,dissection=dissection,
    platform=platform,tech=tech,tags=tags)


@routes.route('/about')
def about():
    return render_template('routes/about.html')


@routes.route('/account',methods=['POST','GET'])
@login_required
def account():
    form = AccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        if current_user.is_admin:
            current_user.about = form.about.data
        if form.profile_pic.data:
            current_user.profile_pic = change_user_pic(form.profile_pic.data)
        db.session.commit()
        flash('Your Info Has Been Updated','success')
        return redirect(url_for('routes.account'))
    else:
        form.username.data = current_user.username
        form.email.data = current_user.email
        if current_user.is_admin:
            form.about.data = current_user.about
    return render_template('routes/account.html', form=form)


@routes.route('/show/articles')
def show_articles():
    page =request.args.get('page',1,type=int)
    articles = Article.query.order_by(Article.timestamp.desc()).paginate(page,per_page=10)
    return render_template('routes/show_articles.html',articles=articles)


@routes.route('/show/category/<int:category_id>')
def show_category(category_id):
    page = request.args.get('page', 1, type=int)
    category = Category.query.get_or_404(category_id)
    articles = Article.query.with_parent(category).order_by(Article.timestamp.desc()).paginate(page, per_page=8)
    return render_template('routes/show_articles.html', articles=articles, selector=category,type='category')


@routes.route('/show/tag/<int:tag_id>')
def show_tag(tag_id):
    page = request.args.get('page', 1, type=int)
    tag = Tag.query.get_or_404(tag_id)
    articles = Article.query.with_parent(tag).order_by(Article.timestamp.desc()).paginate(page, per_page=8)
    return render_template('routes/show_articles.html', articles=articles, selector=tag, type='tag')


@routes.route('/show/review/all')
def show_reviews():
    page = request.args.get('page', 1, type=int)
    articles = Article.query.filter_by(is_review=True).order_by(Article.timestamp.desc()).paginate(page, per_page=8)
    return render_template('routes/show_articles.html', articles=articles,type='reviews')


@routes.route('/show/article/<int:article_id>',methods=['POST','GET'])
def show_article(article_id):
    article = Article.query.get_or_404(article_id)
    article.views_count+=1
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,author=current_user,article=article)
        db.session.add(comment)
        db.session.commit()
        flash('Comment Added','success')
        return redirect(url_for('routes.show_article',article_id=article_id))
    return render_template('routes/show_article.html', article=article,form=form)


@routes.route('/comment/reply/<int:comment_id>',methods=['POST','GET'])
@login_required
def reply_comment(comment_id):
    comment =Comment.query.get_or_404(comment_id)
    form = CommentForm()
    if form.validate_on_submit():
        reply_comment = Comment(body=form.body.data,author=current_user)
        db.session.add(reply_comment)
        comment.replies.append(reply_comment)
        notification = comment_notification(article_id=comment.article.id, receiver=comment.author)
        db.session.add(notification)
        db.session.commit()
        flash('Replay Added','success')
        return redirect_back()
    return render_template('routes/comment.html',form=form,comment=comment)


@routes.route('/comment/edit/<int:comment_id>',methods=['POST','GET'])
@login_required
def edit_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.author:
        abort(403)
    form = CommentForm()
    if form.validate_on_submit():
        comment.body =form.body.data
        db.session.commit()
        flash('Comment Updated','success')
        return redirect_back()
    form.body.data = comment.body
    return render_template('routes/comment.html',form=form,comment=comment)


@routes.route('/comment/delete/<int:comment_id>')
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.author:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('comment deleted','success')
    return redirect_back()


@routes.route('/notifications')
@login_required
def show_notifications():
    filter = request.args.get('filter')
    if filter=='all':
        notifications = Notification.query.all()
    elif filter=='unread':
        notifications = Notification.query.filter_by(is_read=False).all()
    return render_template('routes/notifications.html', notifications=notifications)

@routes.route('/read/notification/<int:notification_id>')
@login_required
def read_notification(notification_id):
    notification=Notification.query.get_or_404(notification_id)
    notification.is_read = True
    db.session.commit()
    flash('notifications archived.', 'success')
    return redirect(url_for('routes.show_notifications'))

@routes.route('/read/notification/all')
@login_required
def read_all_notification():
    for notification in current_user.notification:
        notification.is_read = True
    db.session.commit()
    flash('All notifications archived.', 'success')
    return redirect(url_for('routes.show_notifications'))


@routes.route('/search')
def search():
    if not g.search_form.validate():
        return redirect_back()
    
    page = request.args.get('page',1,type=int)
    articles,total = Article.search(g.search_form.q.data,page,10)
    next_url = url_for('routes.search',q=g.search_form.q.data,page=page+1) if total> page*10 else None
    prev_url = url_for('routes.search', q=g.search_form.q.data,page=page-1) if page>1 else None

    return render_template('search.html',articles=articles,next_url=next_url,prev_url=prev_url)
    

app/templates/index.html
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Amin Template">
    <meta name="keywords" content="Amin, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{%block title%}{%endblock%}</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cinzel:400,700,900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/font-awesome.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/elegant-icons.css')}}" type="text/css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/owl.carousel.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/barfiller.css')}}" type="text/css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/magnific-popup.css')}}" type="text/css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/slicknav.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Humberger Menu Begin -->
    <div class="humberger-menu-overlay"></div>
    <div class="humberger-menu-wrapper">
        <div class="hw-logo">
            <a href="#"><img src="{{url_for('static',filename='logo.png')}}" alt=""></a>
        </div>
        <div class="hw-menu mobile-menu">
            <ul>
                <li><a href="{{url_for('routes.home')}}">Home</a></li>
                <li><a href="{{url_for('routes.show_articles')}}">Articles</a></li>
                <li><a href="{{url_for('routes.show_reviews')}}">Reviews</a></li>
                <li><a href="#">Platforms <i class="fa fa-angle-down"></i></a>
                    <ul class="dropdown">
                        <li><a href="{{url_for('routes.show_category',category_id=1)}}">Windows</a></li>
                        <li><a href="{{url_for('routes.show_category',category_id=2)}}">Playstation</a></li>
                        <li><a href="{{url_for('routes.show_category',category_id=3)}}">Xbox</a></li>
                    </ul>
                </li>
                {%if current_user.is_authenticated%}
                <li><a href="{{url_for('routes.account')}}">Account</a></li>
                {%endif%}
            </ul>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="hw-copyright">
            Copyright © 2021 No Inc. No rights reserved
        </div>
        <div class="hw-social">
            <a href="https://github.com/Mohammed785"><i class="fa fa-github"></i></a>
        </div>
    </div>
    <!-- Humberger Menu End -->

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="ht-options">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-8">
                        <div class="ht-widget">
                            <ul>
                                <li><i class="fa fa-clock-o"></i> {{current_date|dateformater}}</li>
                                {%if not current_user.is_authenticated%}
                                <li class=""><a href="{{url_for('auth.login')}}"><i class="fa fa-sign-in"></a></i> Login
                                <li class=""><a href="{{url_for('auth.register')}}"><i class="fa fa-user-plus"></a></i> Register
                                {%else%}
                                <li class="signup-switch signup-open"><a href="{{url_for('auth.logout')}}"><i class="fa fa-sign-out"></a></i> Logout</li>
                                <li class="signup-switch signup-open"><a href="{{url_for('routes.account')}}"><img src="{{url_for('static',filename='user/'+current_user.profile_pic)}}"class="rounded-circle z-depth-0"height="35"/></a></li>
                                <li class="signup-switch signup-open"><a href="{{url_for('routes.show_notifications')}}" ><i class="fa fa-bell" aria-hidden="true">                                <span id="notification-badge"
                              class="{% if notification_count == 0 %}hide{% endif %} badge badge-danger badge-notification"
                              data-href="{{notifications_count}}">{{ notification_count }}</span>
                                {%endif%}</i></a></li>

                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-4">
                        <div class="ht-social">
                            <a href="https://github.com/Mohammed785"><i class="fa fa-github"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="logo">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                       <a href="{{url_for('routes.home')}}"><img src="{{url_for('static',filename='logo.png')}}" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="nav-options">
            <div class="container">
                <div class="humberger-menu humberger-open">
                    <i class="fa fa-bars"></i>
                </div>
                <div class="nav-search search-switch">
                    <i class="fa fa-search"></i>
                </div>
                <div class="nav-menu">
                    <ul>
                        <li class="active"><a href="{{url_for('routes.home')}}"><span>Home</span></a></li>
                        <li class="mega-menu"><a href="{{url_for('routes.show_tag',tag_id=1)}}"><span>Games</span></a></li>
                        <li><a href="{{url_for('routes.show_tag',tag_id=2)}}"><span>Editors Choice</span></a></li>
                        <li><a href="{{url_for('routes.show_reviews')}}"><span>Reviews</span></a></li>
                        <li><a href="{{url_for('routes.show_category',category_id=5)}}"><span>Discussions</span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </header>
    <div style="background-color: #0d0d0d;">
                {%with messages=get_flashed_messages(with_categories=true)%}
                {%if messages%}
                    {%for category,msg in messages%}
                        <div class="alert alert-{{category}}  alert-dismissible fade show" role="alert">
                            {{ msg }}
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                        </div>
                    {%endfor%}
                {%endif%}
            {%endwith%}
    </div>
    <!-- Header End -->
{%block content%}{%endblock%}
 
    <!-- Footer Section End -->
    <!-- Search model Begin -->
    {%if g.search_form%}
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form" method="GET" action="{{url_for('routes.search')}}">
                {{g.search_form.q(placeholder='Search here...',id='search-input')}}
            </form>
        </div>
    </div>
    {%endif%}
    <!-- Search model end -->

    <!-- Js Plugins -->
    <script src="{{url_for('static',filename='js/jquery-3.3.1.min.js')}}"></script>
    <script src="{{url_for('static',filename='js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static',filename='js/jquery.magnific-popup.min.js')}}"></script>
    <script src="{{url_for('static',filename='js/circle-progress.min.js')}}"></script>
    <script src="{{url_for('static',filename='js/jquery.barfiller.js')}}"></script>
    <script src="{{url_for('static',filename='js/jquery.slicknav.js')}}"></script>
    <script src="{{url_for('static',filename='js/owl.carousel.min.js')}}"></script>
    <script src="{{url_for('static',filename='js/main.js')}}"></script>
</body>

</html>